version: '3'

services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=scircula
      - POSTGRES_USER=root

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "9090:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-conf:/pgadmin

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/opt/app
    ports:
      - "9000:8000"
    depends_on:
      - db

volumes:
  pgadmin-conf:
    external: true
