# Generated by Django 3.0.4 on 2020-03-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('customers', '0002_auto_20200311_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeranalytic',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.ProductSize'),
        ),
    ]
