# Generated by Django 3.0.4 on 2020-03-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20200313_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermeasurement',
            name='bust',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customermeasurement',
            name='hips',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customermeasurement',
            name='thigh',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customermeasurement',
            name='waist',
            field=models.IntegerField(),
        ),
    ]
