# Generated by Django 3.0.4 on 2020-03-31 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20200313_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermeasurement',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Customer'),
        ),
    ]
