# Generated by Django 3.0.5 on 2020-04-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20200311_1128'),
        ('customers', '0005_auto_20200331_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='customer',
            name='vendor',
            field=models.ManyToManyField(blank=True, null=True, to='vendors.Vendor'),
        ),
    ]
