# Generated by Django 3.0.5 on 2020-04-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20200311_1128'),
        ('customers', '0006_auto_20200413_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='vendor',
            field=models.ManyToManyField(blank=True, to='vendors.Vendor'),
        ),
    ]
