# Generated by Django 3.0.6 on 2020-05-28 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200527_1242'),
        ('customers', '0007_auto_20200413_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeranalytic',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='measurements', to='customers.CustomerMeasurement'),
        ),
        migrations.AlterField(
            model_name='customeranalytic',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='analytics', to='products.Product'),
        ),
    ]
