# Generated by Django 3.0.6 on 2020-05-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20200528_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeranalytic',
            name='customer',
        ),
    ]
