# Generated by Django 3.0.6 on 2020-05-28 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200527_1242'),
        ('customers', '0009_remove_customeranalytic_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeranalytic',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.ProductSize'),
        ),
    ]
