# Generated by Django 3.1 on 2020-08-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_auto_20200731_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermeasurement',
            name='inseam',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
