# Generated by Django 3.1 on 2020-08-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_customermeasurement_inseam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermeasurement',
            name='inseam',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
