# Generated by Django 3.1.3 on 2020-11-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_auto_20201125_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeranalytic',
            name='added_to_cart_product_title',
            field=models.CharField(blank=True, default=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='customeranalytic',
            name='purchased_product_title',
            field=models.CharField(blank=True, default=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='customeranalytic',
            name='purchased_size_id',
            field=models.CharField(blank=True, default=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='customeranalytic',
            name='size_added_to_cart_id',
            field=models.CharField(blank=True, default=False, max_length=64),
        ),
    ]
