# Generated by Django 3.2.3 on 2021-05-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_product_size_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeranalytic',
            name='added_to_cart_variant_title',
            field=models.CharField(blank=True, default=False, max_length=256),
        ),
        migrations.AddField(
            model_name='customeranalytic',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customeranalytic',
            name='purchased_variant_title',
            field=models.CharField(blank=True, default=False, max_length=256),
        ),
    ]
