# Generated by Django 3.2.5 on 2021-07-26 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_auto_20210526_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 4, 32, 593011, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 4, 32, 593033, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customeranalytic',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 4, 32, 591474, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customeranalytic',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 4, 32, 591500, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customermeasurement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 4, 32, 592294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customermeasurement',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 4, 32, 592316, tzinfo=utc)),
        ),
    ]
