# Generated by Django 3.2.5 on 2021-07-26 13:05

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0022_auto_20210726_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 5, 29, 607792, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 5, 29, 607818, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customeranalytic',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customeranalytic',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customermeasurement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 5, 29, 606987, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customermeasurement',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 5, 29, 607014, tzinfo=utc)),
        ),
    ]
