# Generated by Django 3.0.6 on 2020-05-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20200311_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='auth_key',
        ),
    ]
