# Generated by Django 3.0.6 on 2020-05-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_remove_vendor_auth_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='valid_till',
        ),
    ]
