# Generated by Django 3.0.6 on 2020-05-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_remove_vendor_valid_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='url',
            field=models.URLField(default='https://scircula.com', unique=True),
            preserve_default=False,
        ),
    ]
