# Generated by Django 3.1 on 2020-09-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='access_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='last_logged',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
