# Generated by Django 3.1 on 2020-09-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_auto_20200911_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='access_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
