# Generated by Django 3.2.3 on 2021-05-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0009_auto_20200911_0948"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendor",
            old_name="url",
            new_name="shop_url",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="access_token",
        ),
        migrations.AddField(
            model_name="vendor",
            name="admin_url",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="vendor",
            name="email",
            field=models.EmailField(default="todo@email.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendor",
            name="integrated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="platform",
            field=models.CharField(default="shopify", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendor",
            name="platform_plan",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="vendor",
            name="scircula_plan",
            field=models.CharField(default="noplan", max_length=64),
        ),
    ]
