# Generated by Django 3.2.3 on 2021-05-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0012_vendor_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="button_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="shop_url",
            field=models.URLField(unique=True),
        ),
    ]
