# Generated by Django 3.2.4 on 2021-06-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_auto_20210525_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='shopify_access_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shopify_subscription_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
