# Generated by Django 3.2.5 on 2021-07-26 12:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0015_alter_vendor_shop_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 12, 50, 51, 192991, tzinfo=utc)),
        ),
    ]
