# Generated by Django 3.2.5 on 2021-07-26 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0016_alter_visit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 4, 32, 598721, tzinfo=utc)),
        ),
    ]
