# Generated by Django 3.2.5 on 2021-08-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0020_auto_20210726_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='returning',
            field=models.BooleanField(default=False),
        ),
    ]
