# Generated by Django 3.2.6 on 2021-09-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0024_auto_20210915_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='script_external_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
