# Generated by Django 3.2.7 on 2021-09-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0025_alter_vendor_script_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='legacy',
            field=models.BooleanField(default=False),
        ),
    ]
