# Generated by Django 3.2.7 on 2021-09-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0026_vendor_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='uninstalled_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
