# Generated by Django 3.2.7 on 2021-09-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0027_vendor_uninstalled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='uninstalled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
