# Generated by Django 3.2.7 on 2021-09-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0029_auto_20210924_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='integration_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='integration_to_be_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='plan_chosen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
