# Generated by Django 3.2.5 on 2021-07-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='external_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
