# Generated by Django 3.2.5 on 2021-07-26 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0015_alter_vendor_shop_url'),
        ('orders', '0002_alter_orderline_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='vendor',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.DO_NOTHING, to='vendors.vendor'),
            preserve_default=False,
        ),
    ]
