# Generated by Django 3.2.5 on 2021-07-26 13:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210726_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 6, 24, 86612, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 6, 24, 86641, tzinfo=utc)),
        ),
    ]
