# Generated by Django 3.0.4 on 2020-03-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_stretch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        )
    ]
