# Generated by Django 3.0.4 on 2020-03-13 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200313_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='pants', on_delete=django.db.models.deletion.DO_NOTHING, to='products.ProductCategory', to_field='name'),
            preserve_default=False,
        ),
    ]
