# Generated by Django 3.0.4 on 2020-03-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productcategoryattribute_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productcategory',
            table='category',
        ),
        migrations.AlterModelTable(
            name='productcategoryattribute',
            table='category_attribute',
        ),
    ]
