# Generated by Django 3.0.4 on 2020-03-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200313_1321'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productcategory',
            table='product_category',
        ),
        migrations.AlterModelTable(
            name='productcategoryattribute',
            table='product_category_attribute',
        ),
    ]
