# Generated by Django 3.0.4 on 2020-03-31 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200313_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='computed_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.ProductSize'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productattribute',
            name='tolerance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductAnalytic',
        ),
    ]
