# Generated by Django 3.0.4 on 2020-03-31 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200331_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategoryattribute',
            old_name='stretch',
            new_name='shift',
        ),
    ]
