# Generated by Django 3.0.4 on 2020-04-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200331_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fabric_and_fit',
            new_name='fabric',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='tags',
            new_name='tag',
        ),
        migrations.AddField(
            model_name='product',
            name='fit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
