# Generated by Django 3.0.6 on 2020-05-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200403_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
