# Generated by Django 3.0.6 on 2020-05-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20200311_1128'),
        ('products', '0014_product_external_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('external_id', 'vendor')},
        ),
    ]
