# Generated by Django 3.0.6 on 2020-05-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200513_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='external_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
