# Generated by Django 3.0.6 on 2020-05-27 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productsize_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='product_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.ProductSize'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sizes', to='products.Product'),
        ),
    ]
