# Generated by Django 3.0.7 on 2020-06-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200608_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategoryattribute',
            name='shift',
            field=models.FloatField(),
        ),
    ]
