# Generated by Django 3.1 on 2020-08-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_inseam'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='inseam',
            field=models.BooleanField(default=False),
        ),
    ]
