# Generated by Django 3.1 on 2020-08-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_productsize_inseam'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='composed',
            field=models.BooleanField(default=False),
        ),
    ]
