# Generated by Django 3.1.3 on 2020-11-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
