# Generated by Django 3.1.3 on 2020-11-26 09:21

from django.db import migrations


def make_many_vendors(apps, schema_editor):
    """
    Create the ProductVendor Objects with vendor and product as foreign key
    and external_id field
    """
    Product = apps.get_model("products", "Product")
    ProductVendor = apps.get_model("products", "ProductVendor")

    for product in Product.objects.all():
        product_vendor = ProductVendor.objects.create(
            product=product, vendor=product.vendor, external_id=product.external_id
        )


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0025_productvendor"),
    ]

    operations = [
        migrations.RunPython(make_many_vendors),
    ]
