# Generated by Django 3.1.4 on 2020-12-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_auto_20200911_0948'),
        ('products', '0032_auto_20201126_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvendor',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvendor',
            name='external_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='productvendor',
            unique_together={('product', 'vendor')},
        ),
    ]
