# Generated by Django 3.1.4 on 2020-12-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20201203_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsizevendor',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
