# Generated by Django 3.1.4 on 2020-12-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_productsizevendor_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvendor',
            unique_together=set(),
        ),
    ]
