# Generated by Django 3.1.5 on 2021-01-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20201230_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvendor',
            name='description',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productvendor',
            name='external_id',
            field=models.TextField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
