# Generated by Django 3.1.5 on 2021-01-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_auto_20200911_0948'),
        ('products', '0035_auto_20201230_1406'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvendor',
            unique_together={('external_id', 'vendor')},
        ),
    ]
