# Generated by Django 3.1.5 on 2021-01-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20210118_0840'),
        ('products', '0036_auto_20210116_1649'),
    ]

    operations = [
    ]
