# Generated by Django 3.1.5 on 2021-01-28 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_merge_20210119_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsizevendor',
            name='product_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productvendor'),
        ),
    ]
