# Generated by Django 3.1.5 on 2021-01-28 08:18

from django.db import migrations, models


def add_product_vendor(apps, schema_editor):
    """
    Set default product vendor
    """
    ProductVendor = apps.get_model("products", "ProductVendor")
    ProductSizeVendor = apps.get_model("products", "ProductSizeVendor")
    for product_size_vendor in ProductSizeVendor.objects.all():
        product_vendors = ProductVendor.objects.filter(
            product=product_size_vendor.product_size.product,
            vendor=product_size_vendor.vendor,
        )
        if len(product_vendors) == 1:
            product_size_vendor.product_vendor = product_vendors[0]
            product_size_vendor.save()


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0038_productsizevendor_product_vendor"),
    ]

    operations = [
        migrations.RunPython(add_product_vendor),
    ]
