# Generated by Django 3.1.5 on 2021-03-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_add_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvendor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
