# Generated by Django 3.2.3 on 2021-05-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_productvendor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvendor',
            name='external_category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
